-- Enable Row Level Security (RLS) is generally recommended, but for this demo start simple.
-- Ideally, enable RLS and policies if user_id management is fully implemented.

-- 1. Create Rooms Table
create table rooms (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null, -- Assuming Supabase Auth
  name text not null,
  type text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Storage Units Table
create table storage_units (
  id bigint generated by default as identity primary key,
  room_id bigint references rooms(id) on delete cascade not null,
  name text not null,
  type text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Create Items Table
create table items (
  id bigint generated by default as identity primary key,
  storage_id bigint references storage_units(id) on delete set null,
  name text not null,
  category text,
  quantity numeric default 1,
  image_url text,
  detected_labels jsonb, -- array of strings from AI
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Create Storage Bucket
-- You must do this in the Supabase Dashboard: Storage -> New Bucket -> 'inventory-images'
-- Make sure it's Public or set proper policies.
-- Policy example for public read:
-- create policy "Public Access" on storage.objects for select using ( bucket_id = 'inventory-images' );
-- Policy example for authenticated upload:
-- create policy "Auth Upload" on storage.objects for insert with check ( bucket_id = 'inventory-images' and auth.role() = 'authenticated' );
